# paasta-delivery-pipeline-service 설정 파일 내용
name: paasta-delivery-pipeline-service                      # 서비스 배포이름(필수)

releases:
- name: paasta-delivery-pipeline-release                    # 서비스 릴리즈 이름(필수)
  version: "1.0"                                        # 서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

update:
  canaries: 1                            # canary 인스턴스 수(필수)
  canary_watch_time: 30000-120000        # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 1                       # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  update_watch_time: 30000-120000        # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)

instance_groups:
- name: mariadb
  azs:
  - z5
  instances: 1
  persistent_disk_type: 2GB
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((internal_network_name))
    static_ips:
    - 10.30.50.68
  templates:
  - name: mariadb
    release: paasta-delivery-pipeline-release

- name: postgres
  azs:
  - z5
  instances: 1
  persistent_disk_type: 2GB
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((internal_network_name))
    static_ips:
    - 10.30.50.82
  templates:
  - name: postgres
    release: paasta-delivery-pipeline-release

- name: inspection
  azs:
  - z5
  instances: 1
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((internal_network_name))
    static_ips:
    - 10.30.50.69
  templates:
  - name: inspection
    release: paasta-delivery-pipeline-release

- name: haproxy
  azs:
  - z5
  instances: 1
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((internal_network_name))
    static_ips:
    - 10.30.50.70
  - name: ((public_network_name))
    static_ips:
    - xxx.xxx.xxx.xxx
  templates:
  - name: haproxy
    release: paasta-delivery-pipeline-release

- name: ci_server
  azs:
  - z5
  instances: 2
  persistent_disk_type: 4GB
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((internal_network_name))
    static_ips:
    - 10.30.50.71
    - 10.30.50.72
  templates:
  - name: ci_server
    release: paasta-delivery-pipeline-release
  env:
    bosh:
      password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0

- name: binary_storage
  azs:
  - z5
  instances: 1
  persistent_disk_type: 4GB
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((internal_network_name))
    static_ips:
    - 10.30.50.39
  jobs:
  - name: binary_storage
    release: paasta-delivery-pipeline-release

- name: delivery-pipeline-common-api
  azs:
  - z5
  instances: 1
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((internal_network_name))
    static_ips:
    - 10.30.50.66
#    - 10.30.107.166
  jobs:
  - name: delivery-pipeline-common-api
    release: paasta-delivery-pipeline-release

- name: delivery-pipeline-inspection-api
  azs:
  - z5
  instances: 1
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((internal_network_name))
    static_ips:
    - 10.30.50.62
#    - 10.30.107.162
  jobs:
  - name: delivery-pipeline-inspection-api
    release: paasta-delivery-pipeline-release

- name: delivery-pipeline-binary-storage-api
  azs:
  - z5
  instances: 1
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((internal_network_name))
    static_ips:
    - 10.30.50.61
  jobs:
  - name: delivery-pipeline-binary-storage-api
    release: paasta-delivery-pipeline-release

- name: delivery-pipeline-api
  azs:
  - z5
  instances: 1
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((internal_network_name))
    static_ips:
    - 10.30.50.65
#    - 10.30.107.165
  jobs:
  - name: delivery-pipeline-api
    release: paasta-delivery-pipeline-release

- name: delivery-pipeline-service-broker
  azs:
  - z5
  instances: 1
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((internal_network_name))
    static_ips:
    - 10.30.50.64
  jobs:
  - name: delivery-pipeline-service-broker
    release: paasta-delivery-pipeline-release

- name: delivery-pipeline-ui
  azs:
  - z5
  instances: 1
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((internal_network_name))
    static_ips:
    - 10.30.50.67
  jobs:
  - name: delivery-pipeline-ui
    release: paasta-delivery-pipeline-release

- name: delivery-pipeline-scheduler
  azs:
  - z5
  instances: 1
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((internal_network_name))
    static_ips:
    - 10.30.50.63
  jobs:
  - name: delivery-pipeline-scheduler
    release: paasta-delivery-pipeline-release

properties:
  cf:                                                      # CLOUD FOUNDRY 설정 정보
    uaa:
      oauth:
        info:
          uri: https://uaa.xxx.xxx.xxx.xxx.xip.io/userinfo
        token:
          check:
            uri: https://uaa.xxx.xxx.xxx.xxx.xip.io/check_token
          access:
            uri: https://uaa.xxx.xxx.xxx.xxx.xip.io/oauth/token
        logout:
          uri: https://uaa.xxx.xxx.xxx.xxx.xip.io/logout.do
        authorization:
          uri: https://uaa.xxx.xxx.xxx.xxx.xip.io/oauth/authorize
        client:
          id: pipeclient
          secret: clientsecret
    api:
      url: https://api.xxx.xxx.xxx.xxx.xip.io/v2/service_instances/[SUID]/permissions

  ci_server:                                               # CI SERVER 설정 정보
    password: '!paas_ta202'
    admin_user:
      username: 'admin'
      password: '!paas_ta202'
    http_url: '10.30'
    http_port: 8088
    ajp13_port: 8009
    ssh:
      username: vcap
      password: c1oudc0w
      port: 22
      identity: "null"                                     # PERM KEY 경로
      key: "null"
    credentials:
      scope: "GLOBAL"
      url: "/credentials/store/system/domain/_"
      class_name: "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
    job:
      name: "ci_server"                                    # JOB 이름과 동일하게 설정
    shared:                                                # Shared 서비스 설정 정보
      urls:
        - http://10.30.50.71:8088
    #    - http://10.30.107.72:8088
    dedicated:                                             # Dedicated 서비스 설정 정보
      urls:
        - http://10.30.50.72:8088
    #    - http://10.30.107.74:8088
    #    - http://10.30.107.75:8088

  mariadb:                                                 # MARIA DB SERVER 설정 정보
    port: 3306
    admin_user:
      password: "!paas_ta202"
    host: 10.30.50.68
    host_names:
    - mariadb0
    host_ips:
    - 10.30.50.68
    datasource:
      url: jdbc:mysql://10.30.50.68:3306/delivery_pipeline?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
      username: root
      password: "!paas_ta202"
      driver_class_name: com.mysql.cj.jdbc.Driver
    jpa:
      database:
        name: mysql

  postgres:                                                # POSTGRESQL SERVER 설정 정보
    port: 5432
    host: 10.30.50.82
    vcap_password: c1oudc0w
    datasource:
      url: jdbc:postgresql://10.30.50.82:5432/sonar
      username: "sonar"
      password: "sonar"
      database: "sonar"

  inspection:                                              # INSPECTION SERVER 설정 정보
    url: 10.30.50.69
    http_url: 'http://10.30.50.69'
    http_port: 9000
    admin:
      username: admin
      password: admin

  binary_storage:                                          # BINARY STORAGE SERVER 설정 정보
    proxy_ip: 10.30.50.39                               # 프록시 서버 IP(swift-keystone job의 static_ip, Object Storage 접속 IP)
    proxy_port: 10008                                      # 프록시 서버 Port(Object Storage 접속 Port)
    username: paasta-pipeline                      # 최초 생성되는 유저이름(Object Storage 접속 유저이름)
    password: paasta-pipeline                      # 최초 생성되는 유저 비밀번호(Object Storage 접속 유저 비밀번호)
    tenantname: paasta-pipeline                    # 최초 생성되는 테넌트 이름(Object Storage 접속 테넌트 이름)
    email: email@email.com                         # 최소 생성되는 유저의 이메일
    binary_desc: "paasta-pipeline-object service"
    container: delivery-pipeline-container
    auth_port: 5000

  common_api:                                              # COMMON API 설정 정보
    url: http://10.30.50.66
    server:
      port: 8081
    authorization:
      id: admin
      password: PaaS-TA
    logging:
      level: INFO
    haproxy:
      urls:
        - 10.30.50.66
#        - 10.30.107.166
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'

  pipeline_api:                                            # CI API 설정 정보
    url: http://10.30.50.65
    server:
      port: 8082
    authorization:
      id: admin
      password: PaaS-TA
    http:
      multipart:
        max_file_size: 1000Mb
        max_request_size: 1000Mb
    logging:
      level: INFO
    haproxy:
      urls:
        - 10.30.50.65
#        - 10.30.107.165
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'

  inspection_api:                                          # INSPECTION API 설정 정보
    url: http://10.30.50.62
    server:
      port: 8083
    http:
      multipart:
        max_file_size: 1000Mb
        max_request_size: 1000Mb
    logging:
      level: INFO
    authorization:
      id: admin
      password: PaaS-TA
    haproxy:
      urls:
        - 10.30.50.62
#        - 10.30.107.162
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'

  binary_storage_api:                                      # BINARY STORAGE API 설정 정보
    http:
      multipart:
        max_file_size: 1000Mb
        max_request_size: 1000Mb
    server:
      port: 8080
    logging:
      level: INFO
    url: http://10.30.50.61
    authorization:
      id: admin
      password: PaaS-TA
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'

  pipeline_ui:                                              # UI 설정 정보
    url: http://10.30.50.67
    server:
      port: 8084
    http:
      multipart:
        max_file_size: 1000Mb
        max_request_size: 1000Mb
    logging:
      level: INFO
    haproxy:
      urls:
        - 10.30.50.67
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'

  pipeline_scheduler:                                      # SCHEDULER 설정 정보
    server:
      port: 8080
    logging:
      level: INFO
    quartz:
      scheduler:
        instance_name: paastaDeliveryPipelineScheduler
        instance_id: AUTO
      thread_pool:
        thread_count: 5
    job:
      start_delay: 0
      repeat_interval: 5000
      description: PaaS-TA Delivery Pipeline Scheduler
      key: StatisticsJob
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'

  pipeline_service_broker:                                 # SERVICE BROKER 설정 정보
    server:
      port: 8080
    logging:
      controller:
        level: INFO
      service:
        level: INFO
    dashboard:
      url: http://xxx.xxx.xxx.xxx:8084/dashboard/[SUID]/
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'

  haproxy:                                                 # HAPROXY 설정 정보
    url: 10.30.50.70
    http_port: 8080

