---
name: paasta-delivery-pipeline                              # 서비스 배포이름(필수) bosh deployments 로 확인 가능한 이름
director_uuid: <%= `bosh status --uuid` %>                  # Director UUID을 입력(필수) bosh status 명령으로 확인 가능
 
releases:
- name: paasta-delivery-pipeline-release                    # 서비스 릴리즈 이름(필수) bosh releases로 확인 가능
  version: latest                                             # 서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

compilation:                                                # 컴파일시 필요한 가상머신의 속성(필수)
  workers: 6                                                # 컴파일 하는 가상머신의 최대수(필수)
  network: default                                          # Networks block에서 선언한 network 이름(필수)
  reuse_compilation_vms: true
  cloud_properties:                                         # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성 (instance_type, availability_zone), 직접 cpu,disk,ram 사이즈를 넣어도 됨
    availability_zone: ap-northeast-2c
    instance_type: c4.large

update:
  canaries: 1                                               # canary 인스턴스 수(필수)
  canary_watch_time: 5000-120000                            # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  update_watch_time: 5000-120000                            # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 1                                          # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  serial: false

networks:                                                   # 네트워크 블록에 나열된 각 서브 블록이 참조 할 수있는 작업이 네트워크 구성을 지정, 네트워크 구성은 네트워크 담당자에게 문의 하여 작성 요망
- name: default
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    dns: [10.0.0.2, 8.8.8.8]                                # DNS 정보
    reserved: ["10.0.0.1 - 10.0.0.69"]                      # 설치시 제외할 IP 설정
    static: ["10.0.0.70 - 10.0.0.99"]
    cloud_properties:
      subnet: subnet-dcf6db91                               # AWS subnet id
      security_groups:
        - default
        - handy-wot-paas-sg

- name: public_network                                      # public network 설정
  type: vip
  cloud_properties: {}

resource_pools:                                             # 배포시 사용하는 resource pools를 명시하며 여러 개의 resource pools 을 사용할 경우 name 은 unique 해야함(필수)
  - name: small                                             # 고유한 resource pool 이름
    network: default
    stemcell:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent         # stemcell 이름(필수)
      version: 3468.21                                       # stemcell 버전(필수)
    cloud_properties:                                       # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성을 설명 (instance_type, availability_zone), 직접 cpu, disk, 메모리 설정가능
      instance_type: t2.micro
      availability_zone: ap-northeast-2c
    env:
      bosh:
        password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0

  - name: small_api
    network: default
    stemcell:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      version: 3468.21
    cloud_properties:
      instance_type: t2.micro
      availability_zone: ap-northeast-2c
    env:
      bosh:
        password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0

  - name: medium
    network: default
    stemcell:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      version: 3468.21
    cloud_properties:
      instance_type: t2.small
      availability_zone: ap-northeast-2c
    env:
      bosh:
        password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0

jobs:
########## INFRA ##########
- name: mariadb
  instances: 1
  resource_pool: small
  persistent_disk: 2048
  networks:
  - name: default
    static_ips:
    - 10.0.0.98
  templates:
  - name: mariadb
    release: paasta-delivery-pipeline-release
  update:
    max_in_flight: 1
    serial: true

- name: postgres
  instances: 1
  resource_pool: small
  persistent_disk: 4096
  networks:
  - name: default
    static_ips:
    - 10.0.0.82
  templates:
  - name: postgres
    release: paasta-delivery-pipeline-release
  update:
    max_in_flight: 1
    serial: true

- name: inspection
  instances: 1
  resource_pool: small
  networks:
  - name: default
    static_ips:
    - 10.0.0.99
  templates:
  - name: inspection
    release: paasta-delivery-pipeline-release
  update:
    max_in_flight: 1
    serial: true

- name: haproxy
  instances: 1
  resource_pool: small
  networks:
  - default:
    - gateway
    - dns
    name: default
    static_ips:
    - 10.0.0.70
  - name: public_network
    static_ips:
    - 52.79.71.78
  templates:
  - name: haproxy
    release: paasta-delivery-pipeline-release
  update:
    max_in_flight: 1
    serial: true

- name: ci_server
  instances: 2
  resource_pool: medium
  persistent_disk: 4096
  networks:
  - name: default
    static_ips:
    - 10.0.0.71
    - 10.0.0.72
  templates:
  - name: ci_server
    release: paasta-delivery-pipeline-release
  update:
    max_in_flight: 1
    serial: true

- name: binary_storage
  instances: 1
  persistent_disk: 10240
  resource_pool: medium
  networks:
  - name: default
    static_ips:
    - 10.0.0.79
  templates:
  - name: binary_storage
    release: paasta-delivery-pipeline-release
  update:
    max_in_flight: 1
    serial: true

########## WEB SERVICE ##########
- name: delivery-pipeline-common-api
  instances: 1
  resource_pool: small_api
  networks:
  - name: default
    static_ips:
    - 10.0.0.96
  templates:
  - name: delivery-pipeline-common-api
    release: paasta-delivery-pipeline-release
  update:
    max_in_flight: 1
    serial: true

- name: delivery-pipeline-inspection-api
  instances: 1
  resource_pool: small_api
  networks:
  - name: default
    static_ips:
    - 10.0.0.92
  templates:
  - name: delivery-pipeline-inspection-api
    release: paasta-delivery-pipeline-release
  update:
    max_in_flight: 1
    serial: true

- name: delivery-pipeline-binary-storage-api
  instances: 1
  resource_pool: small_api
  networks:
  - name: default
    static_ips:
    - 10.0.0.91
  templates:
  - name: delivery-pipeline-binary-storage-api
    release: paasta-delivery-pipeline-release
  update:
    max_in_flight: 1
    serial: true

- name: delivery-pipeline-api
  instances: 1
  resource_pool: small_api
  networks:
  - name: default
    static_ips:
    - 10.0.0.95
  templates:
  - name: delivery-pipeline-api
    release: paasta-delivery-pipeline-release
  update:
    max_in_flight: 1
    serial: true

- name: delivery-pipeline-service-broker
  instances: 1
  resource_pool: small_api
  networks:
  - name: default
    static_ips:
    - 10.0.0.94
  templates:
  - name: delivery-pipeline-service-broker
    release: paasta-delivery-pipeline-release
  update:
    max_in_flight: 1
    serial: true

- name: delivery-pipeline-ui
  instances: 1
  resource_pool: small_api
  networks:
  - name: default
    static_ips:
    - 10.0.0.97
  templates:
  - name: delivery-pipeline-ui
    release: paasta-delivery-pipeline-release
  update:
    max_in_flight: 1
    serial: true

- name: delivery-pipeline-scheduler
  instances: 1
  resource_pool: small_api
  networks:
  - name: default
    static_ips:
    - 10.0.0.93
  templates:
  - name: delivery-pipeline-scheduler
    release: paasta-delivery-pipeline-release
  update:
    max_in_flight: 1
    serial: true

######### PROPERTIES ##########
properties:
  cf:                                                      # CLOUD FOUNDRY 설정 정보
    uaa:
      oauth:
        info:
          uri: https://uaa.wot.paasta-dev.com/userinfo
        token:
          check:
            uri: https://uaa.wot.paasta-dev.com/check_token
          access:
            uri: https://uaa.wot.paasta-dev.com/oauth/token
        logout:
          uri: https://uaa.wot.paasta-dev.com/logout.do
        authorization:
          uri: https://uaa.wot.paasta-dev.com/oauth/authorize
        client:
          id: pipeclient
          secret: clientsecret
    api:
      url: https://api.wot.paasta-dev.com/v2/service_instances/[SUID]/permissions

  ci_server:                                               # CI SERVER 설정 정보
    password: '!paas_ta202'
    admin_user:
      username: 'admin'
      password: '!paas_ta202'
    http_url: 'http://10.0.0.71'
    http_port: 8088
    ajp13_port: 8009
    ssh:
      username: vcap
      password: c1oudc0w
      port: 22
      identity: /home/vcap/key.pem                         # PERM KEY 경로
      key: |+
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEAis2SKcvEOGmAoU6JOXeUFYsWnpoU+dQYWX+YX35YQrlc7UoBufuL4KWGmTkI
        0G8HJsrwuR0wd2BSgKHHO8u/Lg6ns+GlY4Bxfa2gdEFHbAkJ3fCgn17LP833Azf7LrsXi/oEgnzY
        uEXK6tWc+fkzVjUl3vpZGN+U5dM4k6f75rqYiSF7HvKxeK6jT2PrwP98tuNwEnzg3lShaYILQjcI
        AnNi0aIZcln3W45Q9oLT/YLmAqcgpigKAdu05IOpHtY+xZkBLonsWJuJO/gUP81x3Ee0KQSV0J60
        HFFmuE8yhP/4VCyje7B88/kNnXSkwKMsMTHCE8mjiyMLJ5KS3MtN4wIDAQABAoIBABew8suzffBr
        AYuGziFC6cGrldbIUeA6dVWBU86o0APDg7r0sMq/xqY3Wnv4oiqBaOUUKnZOJyGZDTvrYQgxxJXl
        5nXrg8EyAS0EX6i4I6qq+EYrdh79nQ9s5kZkXbkiMeiwaeijypHZR8NBZqO8BykltSsT6/U05EM+
        BCAfwf0lh4lv2pEb/YZd3w6y29VJu6KQomp+AKQsFuglpGGO65xJhYCfFCrGrA/+J8R49bz1Pzjk
        IXTDpvWOlD/K/yFG5ENP4L4paXZAKyk6vLxYUJK+2N40YI7aLL8V0ddC3GDYAirUMBeNxeTRP9iG
        LFyvAWl2LtT1UYKW1wZkSDpEl5ECgYEA0Jx5we0Uhrcv1lV4mrzHcQc4MhDgasYD9Z3Wtzp+R3wC
        bbAkB/OplCG5k3x+yp1Qqvq1lxlByrQCQIcFLIS3PHJ5z6H4kcd3n0HBE7NW27/5/0UmhBTbDFQS
        cs62HJFnvwihNmEkgsvoWU7Yrb3M7bUuRSe3/cUEB5QuY4W+uJ8CgYEAqlV8YLJKOBEyg0Vl+M+6
        nFE8c+Y68Suo5NJLJnXFuXLe84aK6X5w4iKS+NPwq6M6mkdCou7e7h+hev5aNu56PgGNxreuVfOm
        JbkVlvmO9ikiAPAygA92rUquhcLzZrMAj0fUOkHp0kapBEZqa3rdPrPdN15+hvjIPXLRYa0UsD0C
        gYEAoj/Rgz79o/l+P1miv9br18Eht+7gXKs+ER5+DWx1IuwUh3Nj0rt0vT2ttEQz6SqJvzHXYnnG
        bf2rcryRDZr7WQxAKXl0dw2IwFjH7qahe7DIo/4IgtoltGT/JEQZ6AY/hpkTqdPMLd6iDDQC2r6w
        UIGGR0spEzrUc4CQw98WA0kCgYA2wbx2KVqKo5ylbo3VapIG5maUq5KPLQXiaWgXOQ0TDMZ3au0F
        GsyXJZ4xt5BK3PJd3kKhtkCcNDbpHxNJTWimvkEhfLLilqz2u4UhP6ChqZ9wxca2PEJeev+XqJAu
        l6S6atDi2YWdP3HeGfTkEF9HZPLcddge86MLffmpeMaJ0QKBgA3L5wgKXMzf6lM/6hk8Z166pSRn
        cNLJhIKKkTaMdBdi0IlgHNR1G+0fxLDZA9f3203K7ycMvTxM+byihoQK1m0UZ3dkzMw2aS9iq/KN
        rMdCiTUjfm6viXtglRULekdVLSoSOFSTyuIFUh8u6O1hGPHKXoHhEloZEXnWpk8ccGTs
        -----END RSA PRIVATE KEY-----
    credentials:
      scope: "GLOBAL"
      url: "/credentials/store/system/domain/_"
      class_name: "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
    job:
      name: "ci_server"                                    # JOB 이름과 동일하게 설정
    shared:                                                # Shared 서비스 설정 정보
      urls:
        - http://10.0.0.71:8088
    dedicated:                                             # Dedicated 서비스 설정 정보
      urls:
        - http://10.0.0.72:8088

  mariadb:                                                 # MARIA DB SERVER 설정 정보
    port: 3306
    admin_user:
      password: "!paas_ta202"
    host: 10.0.0.98
    host_names:
    - mariadb0
    host_ips:
    - 10.0.0.98
    datasource:
      url: jdbc:mysql://10.0.0.98:3306/delivery_pipeline?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
      username: root
      password: "!paas_ta202"
      driver_class_name: com.mysql.cj.jdbc.Driver
    jpa:
      database:
        name: mysql

  postgres:                                                # POSTGRESQL SERVER 설정 정보
    port: 5432
    host: 10.0.0.82
    vcap_password: c1oudc0w
    datasource:
      url: jdbc:postgresql://10.0.0.82:5432/sonar
      username: "sonar"
      password: "sonar"
      database: "sonar"

  inspection:                                              # INSPECTION SERVER 설정 정보
    url: 10.0.0.99
    http_url: 'http://10.0.0.99'
    http_port: 9000
    admin:
      username: admin
      password: admin

  binary_storage:                                          # BINARY STORAGE SERVER 설정 정보
    proxy_ip: 10.0.0.79                                    # 프록시 서버 IP(swift-keystone job의 static_ip, Object Storage 접속 IP)
    proxy_port: 10008                                      # 프록시 서버 Port (Object Storage 접속 Port)
    default_username: paasta-pipeline                      # 최초 생성되는 유저이름(Object Storage 접속 유저이름)
    default_password: paasta-pipeline                      # 최초 생성되는 유저 비밀번호(Object Storage 접속 유저 비밀번호)
    default_tenantname: paasta-pipeline                    # 최초 생성되는 테넌트 이름(Object Storage 접속 테넌트 이름)
    default_email: email@email.com                         # 최소 생성되는 유저의 이메일
    container: delivery-pipeline-container
    auth_port: 5000

  common_api:                                              # COMMON API 설정 정보
    url: http://10.0.0.70
    server:
      port: 8081
    authorization:
      id: admin
      password: PaaS-TA
    logging:
      level: INFO
    haproxy:
      urls:
        - 10.0.0.96
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'

  pipeline_api:                                            # CI API 설정 정보
    url: http://10.0.0.70
    server:
      port: 8082
    authorization:
      id: admin
      password: PaaS-TA
    http:
      multipart:
        max_file_size: 1000Mb
        max_request_size: 1000Mb
    logging:
      level: INFO
    haproxy:
      urls:
        - 10.0.0.95
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'

  inspection_api:                                          # INSPECTION API 설정 정보
    url: http://10.0.0.70
    server:
      port: 8083
    http:
      multipart:
        max_file_size: 1000Mb
        max_request_size: 1000Mb
    logging:
      level: INFO
    authorization:
      id: admin
      password: PaaS-TA
    haproxy:
      urls:
        - 10.0.0.92
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'

  binary_storage_api:                                      # BINARY STORAGE API 설정 정보
    http:
      multipart:
        max_file_size: 1000Mb
        max_request_size: 1000Mb
    server:
      port: 8080
    logging:
      level: INFO
    url: http://10.0.0.91
    authorization:
      id: admin
      password: PaaS-TA
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'

  pipeline_ui:                                              # UI 설정 정보
    url: http://10.0.0.70
    server:
      port: 8084
    http:
      multipart:
        max_file_size: 1000Mb
        max_request_size: 1000Mb
    logging:
      level: INFO
    haproxy:
      urls:
        - 10.0.0.97
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'

  pipeline_scheduler:                                      # SCHEDULER 설정 정보
    server:
      port: 8080
    logging:
      level: INFO
    quartz:
      scheduler:
        instance_name: paastaDeliveryPipelineScheduler
        instance_id: AUTO
      thread_pool:
        thread_count: 5
    job:
      start_delay: 0
      repeat_interval: 5000
      description: PaaS-TA Delivery Pipeline Scheduler
      key: StatisticsJob
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'

  pipeline_service_broker:                                 # SERVICE BROKER 설정 정보
    server:
      port: 8080
    logging:
      controller:
        level: INFO
      service:
        level: INFO
    dashboard:
      url: http://52.79.71.78:8084/dashboard/[SUID]/
    serviceDefinition:
      id: af86588c-6212-11e7-907b-b6006ad3dps0
      name: delivery-pipeline-v2
      desc: "A paasta source control service for application development.provision parameters : parameters {owner : owner}"
      bindable: true
      planupdatable: true
      plan1:
        id: a5930564-6212-11e7-907b-b6006ad3dps1
        name: delivery-pipeline-shared
        desc: "This is a shared service plan. All services are created equally."
        type: A
      plan2:
        id: a5930564-6212-11e7-907b-b6006ad3dps2
        name: delivery-pipeline-dedicated
        desc: "This is a dedicated service plan. All services are created equally."
        type: B
    java_opts: '-XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K -Xmx681574K'
 
  haproxy:                                                 # HAPROXY 설정 정보
    url: 10.0.0.70
    http_port: 8080

